/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardInquiriesRouteImport } from './routes/dashboard/inquiries'
import { Route as AuthMeRouteImport } from './routes/auth/me'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings.index'
import { Route as DashboardNotificationsIndexRouteImport } from './routes/dashboard/notifications.index'
import { Route as DashboardInquiriesIndexRouteImport } from './routes/dashboard/inquiries.index'
import { Route as DashboardInquiriesIdRouteImport } from './routes/dashboard/inquiries.$id'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInquiriesRoute = DashboardInquiriesRouteImport.update({
  id: '/dashboard/inquiries',
  path: '/dashboard/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMeRoute = AuthMeRouteImport.update({
  id: '/auth/me',
  path: '/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardNotificationsIndexRoute =
  DashboardNotificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardNotificationsRoute,
  } as any)
const DashboardInquiriesIndexRoute = DashboardInquiriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardInquiriesRoute,
} as any)
const DashboardInquiriesIdRoute = DashboardInquiriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardInquiriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/resume': typeof ResumeRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/me': typeof AuthMeRoute
  '/dashboard/inquiries': typeof DashboardInquiriesRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/dashboard/inquiries/$id': typeof DashboardInquiriesIdRoute
  '/dashboard/inquiries/': typeof DashboardInquiriesIndexRoute
  '/dashboard/notifications/': typeof DashboardNotificationsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/resume': typeof ResumeRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/me': typeof AuthMeRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects': typeof ProjectsIndexRoute
  '/dashboard/inquiries/$id': typeof DashboardInquiriesIdRoute
  '/dashboard/inquiries': typeof DashboardInquiriesIndexRoute
  '/dashboard/notifications': typeof DashboardNotificationsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/resume': typeof ResumeRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/me': typeof AuthMeRoute
  '/dashboard/inquiries': typeof DashboardInquiriesRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/dashboard/inquiries/$id': typeof DashboardInquiriesIdRoute
  '/dashboard/inquiries/': typeof DashboardInquiriesIndexRoute
  '/dashboard/notifications/': typeof DashboardNotificationsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/resume'
    | '/api/health'
    | '/auth/error'
    | '/auth/me'
    | '/dashboard/inquiries'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/projects/$slug'
    | '/projects/'
    | '/dashboard/inquiries/$id'
    | '/dashboard/inquiries/'
    | '/dashboard/notifications/'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/resume'
    | '/api/health'
    | '/auth/error'
    | '/auth/me'
    | '/projects/$slug'
    | '/projects'
    | '/dashboard/inquiries/$id'
    | '/dashboard/inquiries'
    | '/dashboard/notifications'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/resume'
    | '/api/health'
    | '/auth/error'
    | '/auth/me'
    | '/dashboard/inquiries'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/projects/$slug'
    | '/projects/'
    | '/dashboard/inquiries/$id'
    | '/dashboard/inquiries/'
    | '/dashboard/notifications/'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ResumeRoute: typeof ResumeRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthMeRoute: typeof AuthMeRoute
  DashboardInquiriesRoute: typeof DashboardInquiriesRouteWithChildren
  DashboardNotificationsRoute: typeof DashboardNotificationsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/inquiries': {
      id: '/dashboard/inquiries'
      path: '/dashboard/inquiries'
      fullPath: '/dashboard/inquiries'
      preLoaderRoute: typeof DashboardInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/me': {
      id: '/auth/me'
      path: '/auth/me'
      fullPath: '/auth/me'
      preLoaderRoute: typeof AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/notifications/': {
      id: '/dashboard/notifications/'
      path: '/'
      fullPath: '/dashboard/notifications/'
      preLoaderRoute: typeof DashboardNotificationsIndexRouteImport
      parentRoute: typeof DashboardNotificationsRoute
    }
    '/dashboard/inquiries/': {
      id: '/dashboard/inquiries/'
      path: '/'
      fullPath: '/dashboard/inquiries/'
      preLoaderRoute: typeof DashboardInquiriesIndexRouteImport
      parentRoute: typeof DashboardInquiriesRoute
    }
    '/dashboard/inquiries/$id': {
      id: '/dashboard/inquiries/$id'
      path: '/$id'
      fullPath: '/dashboard/inquiries/$id'
      preLoaderRoute: typeof DashboardInquiriesIdRouteImport
      parentRoute: typeof DashboardInquiriesRoute
    }
  }
}

interface DashboardInquiriesRouteChildren {
  DashboardInquiriesIdRoute: typeof DashboardInquiriesIdRoute
  DashboardInquiriesIndexRoute: typeof DashboardInquiriesIndexRoute
}

const DashboardInquiriesRouteChildren: DashboardInquiriesRouteChildren = {
  DashboardInquiriesIdRoute: DashboardInquiriesIdRoute,
  DashboardInquiriesIndexRoute: DashboardInquiriesIndexRoute,
}

const DashboardInquiriesRouteWithChildren =
  DashboardInquiriesRoute._addFileChildren(DashboardInquiriesRouteChildren)

interface DashboardNotificationsRouteChildren {
  DashboardNotificationsIndexRoute: typeof DashboardNotificationsIndexRoute
}

const DashboardNotificationsRouteChildren: DashboardNotificationsRouteChildren =
  {
    DashboardNotificationsIndexRoute: DashboardNotificationsIndexRoute,
  }

const DashboardNotificationsRouteWithChildren =
  DashboardNotificationsRoute._addFileChildren(
    DashboardNotificationsRouteChildren,
  )

interface DashboardSettingsRouteChildren {
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ResumeRoute: ResumeRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthMeRoute: AuthMeRoute,
  DashboardInquiriesRoute: DashboardInquiriesRouteWithChildren,
  DashboardNotificationsRoute: DashboardNotificationsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
