/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as DashboardInquiriesRouteImport } from './routes/dashboard/inquiries'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthMeRouteImport } from './routes/auth/me'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardInquiriesIndexRouteImport } from './routes/dashboard/inquiries.index'
import { Route as DashboardInquiriesIdRouteImport } from './routes/dashboard/inquiries.$id'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInquiriesRoute = DashboardInquiriesRouteImport.update({
  id: '/dashboard/inquiries',
  path: '/dashboard/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMeRoute = AuthMeRouteImport.update({
  id: '/auth/me',
  path: '/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInquiriesIndexRoute = DashboardInquiriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardInquiriesRoute,
} as any)
const DashboardInquiriesIdRoute = DashboardInquiriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardInquiriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/resume': typeof ResumeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/me': typeof AuthMeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/inquiries': typeof DashboardInquiriesRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/dashboard/inquiries/$id': typeof DashboardInquiriesIdRoute
  '/dashboard/inquiries/': typeof DashboardInquiriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/resume': typeof ResumeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/me': typeof AuthMeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/dashboard/inquiries/$id': typeof DashboardInquiriesIdRoute
  '/dashboard/inquiries': typeof DashboardInquiriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/resume': typeof ResumeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/me': typeof AuthMeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/inquiries': typeof DashboardInquiriesRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/dashboard/inquiries/$id': typeof DashboardInquiriesIdRoute
  '/dashboard/inquiries/': typeof DashboardInquiriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/resume'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/me'
    | '/blog/$slug'
    | '/dashboard/inquiries'
    | '/projects/$slug'
    | '/blog/'
    | '/projects/'
    | '/dashboard/inquiries/$id'
    | '/dashboard/inquiries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/resume'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/me'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/blog'
    | '/projects'
    | '/dashboard/inquiries/$id'
    | '/dashboard/inquiries'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/resume'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/me'
    | '/blog/$slug'
    | '/dashboard/inquiries'
    | '/projects/$slug'
    | '/blog/'
    | '/projects/'
    | '/dashboard/inquiries/$id'
    | '/dashboard/inquiries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ResumeRoute: typeof ResumeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthMeRoute: typeof AuthMeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DashboardInquiriesRoute: typeof DashboardInquiriesRouteWithChildren
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/inquiries': {
      id: '/dashboard/inquiries'
      path: '/dashboard/inquiries'
      fullPath: '/dashboard/inquiries'
      preLoaderRoute: typeof DashboardInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/me': {
      id: '/auth/me'
      path: '/auth/me'
      fullPath: '/auth/me'
      preLoaderRoute: typeof AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/inquiries/': {
      id: '/dashboard/inquiries/'
      path: '/'
      fullPath: '/dashboard/inquiries/'
      preLoaderRoute: typeof DashboardInquiriesIndexRouteImport
      parentRoute: typeof DashboardInquiriesRoute
    }
    '/dashboard/inquiries/$id': {
      id: '/dashboard/inquiries/$id'
      path: '/$id'
      fullPath: '/dashboard/inquiries/$id'
      preLoaderRoute: typeof DashboardInquiriesIdRouteImport
      parentRoute: typeof DashboardInquiriesRoute
    }
  }
}

interface DashboardInquiriesRouteChildren {
  DashboardInquiriesIdRoute: typeof DashboardInquiriesIdRoute
  DashboardInquiriesIndexRoute: typeof DashboardInquiriesIndexRoute
}

const DashboardInquiriesRouteChildren: DashboardInquiriesRouteChildren = {
  DashboardInquiriesIdRoute: DashboardInquiriesIdRoute,
  DashboardInquiriesIndexRoute: DashboardInquiriesIndexRoute,
}

const DashboardInquiriesRouteWithChildren =
  DashboardInquiriesRoute._addFileChildren(DashboardInquiriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ResumeRoute: ResumeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthMeRoute: AuthMeRoute,
  BlogSlugRoute: BlogSlugRoute,
  DashboardInquiriesRoute: DashboardInquiriesRouteWithChildren,
  ProjectsSlugRoute: ProjectsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
